server:
  port: 8087
 
 
  
spring: 
  datasource: 
    username: root
    password: ipLyb#654321
    url: jdbc:mysql://47.92.70.34:3306/wlk_test?useUnicode=true&amp;characterEncoding=utf-8&allowMultiQueries=true&&useSSL=false


      